#!/usr/bin/expect -f

#init params
set server [lindex $argv 0]
set user   [lindex $argv 1]
set pass   [lindex $argv 2]
set timeout 10

#clean existing certificat
 exec /opt/puppetlabs/bin/puppet cert clean $server


#clear existing ssl repo of agent
spawn ssh -oStrictHostKeyChecking=no $user@$server "rm -rf /etc/puppetlabs/puppet/ssl/*"
expect "Password:"
send "$pass\r"
sleep 2
#clean existing certificat
#exec /opt/puppetlabs/bin/puppet cert clean $server

#Generate client certificat
spawn ssh -oStrictHostKeyChecking=no $user@$server "puppet agent --test --noop --environment work --server puppet-rec"
expect "Password:"
send "$pass\r"
sleep 6

#Sign certificat on master
 exec /opt/puppetlabs/bin/puppet cert sign $server
sleep 1
#Exec new -test -noop
spawn ssh -oStrictHostKeyChecking=no $user@$server "puppet agent --test --noop --environment work --server puppet-rec"
expect "Password:"
send "$pass\r"
